name: Mark stale pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: 'awaiting-reporter-response,missing-details'
        days-before-issue-stale: 14
        days-before-issue-close: 7
        stale-issue-label: 'stale'
        stale-issue-message: 'This issue was marked as needing more information from the reporter. It will automatically close in 7 days if there is no response. If you are still experiencing this issue, please respond with the requested information.'
        close-issue-message: 'This issue was automatically closed due to no response from the reporter after requesting more information. Please feel free to reopen if you can provide the requested details.'
        exempt-issue-labels: 'evergreen,bug,feature-request,investigating,awaiting-team'
        days-before-pr-stale: 16
        days-before-pr-close: 14
        stale-pr-message: 'This PR has not seen any updates in the last 16 days. Without further action this PR will be closed in 14 days. To disable further staleness checks add the `evergreen` label.'
        close-pr-message: 'This PR has seen no updates in the past 30 days and will now be closed. Restore the branch and create a new PR if you wish to continue work.'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'evergreen'
        operations-per-run: 300
